.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/api/DialogmeldingApi.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/application/api/authentication/ApiFeature.kt, src/main/kotlin/no/nav/syfo/application/api/authentication/JwtIssuer.kt
Den skal kunne godta både systemkall og OnBehalfOf-flow, men til å begynne med kommer det kun til komme systemkall fra fastlegerest.
Godta fastlegerest, ved å legge til en identifier til clientId i acceptedAudience. I følge nais doc skal det være ekvivalent med å legge inn selve clientIDen.
"AZURE_APP_WELL_KNOWN_URL" får man tilgang til gjennom azurator, så man trenger ikke eksplisitt sette den i naiserator-filene.
=> Add authentication with Azure V2 to api

src/test/kotlin/no/nav/syfo/oppfolgingsplan/OppfolgingsplanServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FellesformatMessageXml.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/RSHodemeldingGenerator.kt
"Fasit-meldingen" er hentet fra dialogfordeleren, bare endret noen navn, pluss ekstra escapes foran spørsmålstegn og paranteser, for at det skal fungere når man gjør om til Regex.
Grunnen til at man bruker Regex, er for å alltid kunne matche på tid og uuid, som varierer mellom hver kjøring.
=> Add test for OppfolgingsplanService, verify sent message is correct

src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/application/database/Database.kt, src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt, src/main/kotlin/no/nav/syfo/behandler/api/BehandlerApi.kt, src/main/kotlin/no/nav/syfo/behandler/api/BehandlerDialogmeldingDTO.kt, src/main/kotlin/no/nav/syfo/behandler/database/BehandlerDialogmeldingQuery.kt, src/main/kotlin/no/nav/syfo/behandler/database/domain/PBehandlerDialogmelding.kt, src/main/kotlin/no/nav/syfo/behandler/domain/Behandler.kt, src/main/kotlin/no/nav/syfo/behandler/domain/BehandlerType.kt, src/main/kotlin/no/nav/syfo/behandler/domain/Fastlege.kt, src/main/kotlin/no/nav/syfo/behandler/fastlege/FastlegeResponse.kt, src/main/kotlin/no/nav/syfo/domain/Virksomhetsnummer.kt, src/test/kotlin/no/nav/syfo/behandler/BehandlerServiceSpek.kt, src/test/kotlin/no/nav/syfo/behandler/api/BehandlerApiSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FastlegeResponseGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/PartnerinfoResponseGenerator.kt
Ved kall for å hente behandler hentes aktiv fastlege med partnerId for arbeidstaker.
Det sjekkes om det finnes behandler i databasen med samme partnerId (og om den er knyttet til arbeidstakeren). 
- Dersom behandler finnes vil denne returneres (og knyttes til arbeidstakeren hvis den ikke er det eller ikke er siste behandler knyttet til til arbeidstakeren)
- Dersom behandler ikke finnes vil denne lagres, knyttes til arbeidstakeren og returneres.
=> Lagt til henting og lagring av behandler som kan motta dialogmelding (for aktiv fastlege)

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
Fastlegerest is only in GCP, and the access policy for FSS is therefore removed.
=> Remove unused access policy

src/main/kotlin/no/nav/syfo/behandler/partnerinfo/PartnerinfoClient.kt, src/main/kotlin/no/nav/syfo/behandler/partnerinfo/PartnerinfoMetric.kt, src/test/kotlin/no/nav/syfo/behandler/BehandlerServiceSpek.kt, src/test/kotlin/no/nav/syfo/behandler/api/BehandlerApiSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/mocks/FastlegeRestMock.kt, src/test/kotlin/no/nav/syfo/testhelper/mocks/SyfopartnerInfoMock.kt
I noen tilfeller finner vi flere partnerId-er for en herId - da vil den høyeste id-en være den nyeste og sannsynligvis den mest riktige å bruke for sending av dialogmelding.
=> Return largest partnerId. Add metric and logging.

src/main/kotlin/no/nav/syfo/behandler/kafka/dialogmeldingfrombehandler/KafkaDialogmeldingFromBehandler.kt, src/main/kotlin/no/nav/syfo/util/JAXB.kt, src/main/kotlin/no/nav/syfo/util/XMLUtil.kt, src/test/kotlin/no/nav/syfo/util/XMLUtilSpek.kt
Da slipper vi å sende inn klassen som parameter til funksjonene.
Gjør private funksjoner om til internal med PublishedApi-annotasjon så de kan kalles fra inline funksjoner.
https://stackoverflow.com/questions/45949584/how-does-the-reified-keyword-in-kotlin-work
=> Make XML generic functions inline

src/main/kotlin/no/nav/syfo/dialogmelding/converter/MottakerConverter.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FellesformatDialogmeldingAvlysningXml.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FellesformatDialogmeldingEndreTidStedXml.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FellesformatDialogmeldingReferatXml.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FellesformatDialogmeldingXml.kt
According to the documentation:
nav-veiledning-bruk-av-dialogmelding-ia-v-1-5-04.12.2015.pdf, the section
is not in use.
Co-authored-by: John Martin Lindseth <john.martin.lindseth@nav.no>
=> Remove role to patient section from dialogmelding to behandler

src/main/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaBehandlerSykmelding.kt, src/main/kotlin/no/nav/syfo/util/StringUtil.kt, src/test/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaSykmeldingSpek.kt
Har kikket litt på det vi har i prod-databasen, og det viser seg at vi *ikke* kapitaliserer navn for leger fra fastlegerest (fastlegerrest kapitaliserer navn, men bare for pasient/arbeidstaker), så de behandlerne vi har i databasen til isdialogmelding nå har navn med store bokstaver. Så da tror jeg det riktigste blir å ta inn behandlere fra sykmeldinger as-is, og så kan vi se nærmere på behovet for å gjøre noe med disse navnene før de sendes til frontend (evnt transformere i frontend).
=> Remove name capitalization for sykmelding

.nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationUtils.kt, src/main/kotlin/no/nav/syfo/application/database/Database.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/KafkaModule.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaBehandlerSykmelding.kt
Ideen er å deploye dette i prod for å få prosessert 1000 sykmeldinger per pod. Dette vil generere behandlere i databasen som vi kan sjekke om ble som forventet etterpå. 
Planlegger å revertere det meste av koden etterpå i en ny PR, og så komme tilbake med enda en PR som skrur det på slik at hele backlog'en av sykmeldinger blir prosessert (det er antakelig flere millioner).
=> Process limited number of sykmelding

.nais/naiserator-prod.yaml
Skru av midlertidig mens vi undersøker problemet med at cronJob'en ikke fungerer som den skal.
=> Disable sykmelding prod (temporarily)

src/main/kotlin/no/nav/syfo/behandler/domain/Behandler.kt, src/test/kotlin/no/nav/syfo/behandler/kafka/dialogmeldingfrombehandler/KafkaDialogmeldingFromBehandlerSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmeldingFromBehandlerGenerator.kt
Med dette slipper vi å få warnings av denne typen i loggen: 
Can't find behandleridenter in dialogmelding from behandler: navLogId: 2207270838sknl16325.1, msgId: c3a39ebf-a3ea-435a-9233-aedf008d90f0
=> Accept all valid ident types

src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt
Søkestrengen i frontend kan bli oppdatert til å inneholde kolon idet man velger en behandler. Formatet er da "etternavn, fornavn: kontor", og søket vil kun slå ut på kontor. Ved å fjerne kolon fra stringen vil vi da få søkt på hele navnet. I tillegg så chaines replace-kallene, i stedet for å ha mange maps.
=> Replace colon in search

src/main/kotlin/no/nav/syfo/application/database/Database.kt
Foreslår at vi prøver ut dette i en app for å løse problemet med sporadiske feil mot databasen av denne typen: org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update
=> Use transaction isolation level READ_COMMITTED

src/main/kotlin/no/nav/syfo/behandler/database/BehandlerExtendedQuery.kt, src/main/kotlin/no/nav/syfo/behandler/database/BehandlerQuery.kt, src/main/kotlin/no/nav/syfo/behandler/database/domain/PBehandler.kt, src/main/kotlin/no/nav/syfo/behandler/domain/Behandler.kt, src/main/resources/db/migration/V3_0__alter_table_behandler_add_column_invalidated.sql, src/test/kotlin/no/nav/syfo/behandler/api/BehandlerApiSpek.kt
Legger til rette for at behandlere kan invalideres. 
I neste PR tenkte jeg å invalidere behandlere der vi mottar apprec med status 2 og feilmelding: Avvist, E21, Mottaker finnes ikke
=> Invalidation timestamp field for behandler

src/main/resources/db/migration/V3_4__disable_duplicate_kontor.sql
Dette håndterer den første problemet rapporert av e-mottak.
=> Fix invalid partner

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/client/veiledertilgang/Tilgang.kt, src/main/kotlin/no/nav/syfo/client/veiledertilgang/TilgangskontrollClientMetric.kt, src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt, src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/mocks/MockHttpClient.kt, src/test/kotlin/no/nav/syfo/testhelper/mocks/SyfoTilgangskontrollMock.kt
Endrer fra syfo-tilgangskontroll til istilgangskontroll
=> IS-1689: Use istilgangskontroll

src/main/kotlin/no/nav/syfo/dialogmelding/converter/MottakenhetBlokkConverter.kt, src/test/kotlin/no/nav/syfo/dialogmelding/converter/FellesformatConverterSpek.kt
These partnerIDs have been wrong since the kontor changed to Helseplattformen, so meldinger have been sent to a disabled Helsenett inbox.
Now we change the partnerID before sending the melding to emottak, so they can route the message correctly.
Use hard coded id's because we don't expect them to change soon, and no more kontor will be added soon.
=> IS-1913: Replace partnerID for HP kontor

src/main/resources/db/migration/V5_1__resend_failed_message.sql
It was sent to the wrong email server in Helsenett, due to mismatch of kontor herID. https://github.com/navikt/isdialogmelding/pull/274
=> IS-1917: Resend message that failed

src/main/resources/db/migration/V5_2__resend_failed_messages.sql
This resends messages from two kontor sent on or after 1 dec.
List of uuids was manually fetched from DB based on messages sent to behandlere on the two kontor.
See also:
IS-193: https://github.com/navikt/isdialogmelding/pull/274
IS-1917: https://github.com/navikt/isdialogmelding/pull/275
=> IS-1918: Resend messages to HP that failed

src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
Gi lps-oppfolgingsplan-mottak tillatelse til å aksessere OppfolgingsplanSystemApi
lps-oppfolgingsplan-mottak kan nå gjøre POST kall mot `.../api/v2/send/oppfolgingsplan`
for å sende Altinn-LPS til fastlege.
=> Authorize lps-oppfolgingsplan-mottak to access OppfolgingsplanSystemApi

src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt
Har fått invalidert mange behandlere (over 5000 forekomster) som var deaktivert i adresseregisteret.
Lager fortsatt en del følgefeil (særlig i fastlegerest og syfohelsenettproxy), så deaktiverer inntil vi har noe nytt for den å gjøre.
=> IS-1821: Disable cronjob for now

src/main/resources/db/migration/V6_2__disable_behandler_kontor.sql
Fått en beskjed fra e-mottak om et kontor som ikke kan motta dialogmeldinger lengre.
Kontoret med id 1926 er fortsatt aktivt, men har ingen behandlere i Adresseregisteret.
Kontorene med id 1501 og 2103 er deaktivterte i Adresseregisteret.
=> IS-1946: Invalider kontor og tilhørende behandlere

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/cronjob/SuspensjonCronjob.kt
https://nav-it.slack.com/archives/C012X71FN04/p1713185536067369
=> Btsys migrated to gcp

src/main/resources/db/migration/V7_01__activate_kontor.sql
Vanligvis skjer dette når vi mottar en dialogmelding fra kontoret, men her forventes det tydeligvis at NAV skal kunne sende melding først.
=> IS-2591: Aktivere behandlerkontor

src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt, src/test/kotlin/no/nav/syfo/behandler/BehandlerServiceSpek.kt
Oppdaget i forbindelse med en jira-sak at vi lager duplikate koblinger mellom behandler og arbeidstaker når behandler har blitt suspendert.
=> IS-2559: Ikke lage duplikate relasjoner for suspenderte behandlere

src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaBehandlerSykmelding.kt, src/test/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaSykmeldingSpek.kt
Siden vi går over til å hente behandlere fra Adresseregisteret bør vi slutte med å opprette behandlere fra sykmeldinger (men fortsette med å opprette behandlerkontor og relasjoner mellom behandler og arbeidstaker).
=> IS-2406: Ikke lagre behandler fra sykmelding

.github/dependabot.yaml, README.md, build.gradle.kts
Sånn at dependabot finner avhengigheter og lagrer ukentige PRs på oppdateringer. Grupperer minor og patch-oppdatering i samme PR.
Gjorde også forenkling av bygge-config inspirert av https://github.com/navikt/isdialogmote/
=> Fix dependabot etc

src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt, src/test/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
Vi har en behandler som har byttet fnr (og ikke fra dnr). Vil ikke skje så ofte, så det enkleste er å instruere cronjob'en om å oppdatere akkurat denne behandleren (dvs med spesifikk behandlerRef) fra Adresseregisteret.
=> IS-2732: Oppdatere spesifikk behandler fra Adresseregisteret

.nais/kafka/behandler-dialogmelding-bestilling.yaml, .nais/kafka/behandler-dialogmelding-status.yaml, .nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
AAP skal bruke vår løsning for å sende dialogmeldinger (forespørsel om legeerklæring).
=> IS-2721: Gi tilgang til AAP
