src/main/kotlin/no/nav/syfo/application/mq/MQSender.kt, src/main/kotlin/no/nav/syfo/oppfolgingsplan/OppfolgingsplanService.kt
Etter at man har laget Fellesformat av RSHodemeldingen fra fastlegerest, må vi sende den marshallede meldingen til emottak over MQ.
=> Send Oppfolgingsplan to emottak with mqSender

src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
Fjern "allowNull"-metoden, siden vi nå krever at alt er på plass for at appen skal fungere.
Flytt også på rekkefølgen, så MQ-variablene ligger i samme rekkefølge som i naiserator-filene
=> Require envVars

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/partnerinfo/PartnerinfoClient.kt, src/main/kotlin/no/nav/syfo/partnerinfo/PartnerinfoMetric.kt, src/main/kotlin/no/nav/syfo/partnerinfo/PartnerinfoResponse.kt
Tester denne også når den tas i bruk i APIet for å hente behandlere som man kan motta dialogmelding.
=> add partnerinfo client

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt, src/main/kotlin/no/nav/syfo/behandler/api/BehandlerApi.kt, src/main/kotlin/no/nav/syfo/behandler/api/BehandlerDialogmeldingDTO.kt, src/main/kotlin/no/nav/syfo/behandler/domain/Fastlege.kt, src/main/kotlin/no/nav/syfo/behandler/fastlege/FastlegeClient.kt, src/main/kotlin/no/nav/syfo/behandler/fastlege/FastlegeMetric.kt, src/main/kotlin/no/nav/syfo/behandler/fastlege/FastlegeResponse.kt, src/main/kotlin/no/nav/syfo/behandler/partnerinfo/PartnerinfoClient.kt, src/main/kotlin/no/nav/syfo/behandler/partnerinfo/PartnerinfoMetric.kt, src/main/kotlin/no/nav/syfo/behandler/partnerinfo/PartnerinfoResponse.kt, src/main/kotlin/no/nav/syfo/util/RequestUtil.kt, src/test/kotlin/no/nav/syfo/behandler/api/BehandlerApiSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/JWTUtil.kt, src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FastlegeResponseGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/PartnerinfoResponseGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/mocks/AzureADMock.kt, src/test/kotlin/no/nav/syfo/testhelper/mocks/FastlegeRestMock.kt, src/test/kotlin/no/nav/syfo/testhelper/mocks/SyfopartnerInfoMock.kt, src/test/resources/jwkset.json
Henter per nå kun aktiv fastlege med partnerinfo
=> api for behandler som kan motta dialogmelding

src/main/kotlin/no/nav/syfo/behandler/api/BehandlerDialogmeldingDTO.kt, src/main/kotlin/no/nav/syfo/behandler/domain/BehandlerType.kt, src/main/kotlin/no/nav/syfo/behandler/domain/Fastlege.kt, src/main/kotlin/no/nav/syfo/behandler/fastlege/FastlegeClient.kt, src/main/kotlin/no/nav/syfo/behandler/fastlege/FastlegeResponse.kt, src/test/kotlin/no/nav/syfo/behandler/api/BehandlerApiSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FastlegeResponseGenerator.kt
+ Gjort noen felter optional og rettet path til fastlegerest
=> Lagt til behandler-type og kontor i DTO

src/main/resources/db/migration/V1_2__create_table_behandler_dialogmelding.sql
Utkast til tabeller for å lagre behandlere som kan motta dialogmelding for sykmeldte arbeidstakere
=> add table behandler_dialogmelding med kobling til at

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, build.gradle.kts, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/JacksonKafkaDeserializer.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/KafkaBehandlerDialogmeldingBestilling.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/KafkaConfig.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/KafkaMetric.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/KafkaModule.kt, src/test/kotlin/no/nav/syfo/testhelper/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/TestKafka.kt
=> Send dialogmelding til behandler (del 1)

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/application/ApplicationUtils.kt, src/main/kotlin/no/nav/syfo/behandler/BehandlerDialogmeldingService.kt, src/main/kotlin/no/nav/syfo/behandler/database/BehandlerDialogmeldingBestillingQuery.kt, src/main/kotlin/no/nav/syfo/behandler/database/BehandlerDialogmeldingQuery.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/KafkaModule.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobMetric.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/DialogmeldingCronjob.kt, src/main/kotlin/no/nav/syfo/cronjob/DialogmeldingCronjobResult.kt, src/main/kotlin/no/nav/syfo/cronjob/DialogmeldingCronjobRunner.kt, src/main/kotlin/no/nav/syfo/cronjob/DialogmeldingSendCronjob.kt, src/main/kotlin/no/nav/syfo/cronjob/leaderelection/LeaderPodClient.kt, src/main/kotlin/no/nav/syfo/cronjob/leaderelection/LeaderPodDTO.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Cronjob'en gjør i første omgang ikke annet enn å sette dialogmeldingen som sendt.
=> Send dialogmelding til behandler (del 5): cronjob

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/behandler/BehandlerDialogmeldingService.kt, src/main/kotlin/no/nav/syfo/behandler/database/domain/PBehandlerDialogmeldingBestilling.kt, src/main/kotlin/no/nav/syfo/behandler/domain/BehandlerDialogmeldingArbeidstaker.kt, src/main/kotlin/no/nav/syfo/behandler/domain/BehandlerDialogmeldingBestilling.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/BehandlerDialogmeldingBestillingDTO.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/KafkaBehandlerDialogmeldingBestilling.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/KafkaModule.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/dialogmelding/DialogmeldingService.kt, src/main/kotlin/no/nav/syfo/dialogmelding/converter/DialogmeldingConverter.kt, src/main/kotlin/no/nav/syfo/dialogmelding/converter/DokumentDialogmeldingConverter.kt, src/main/kotlin/no/nav/syfo/dialogmelding/converter/DokumentVedleggConverter.kt, src/main/kotlin/no/nav/syfo/dialogmelding/converter/FellesformatConverter.kt, src/main/kotlin/no/nav/syfo/dialogmelding/converter/HodemeldingConverter.kt, src/main/kotlin/no/nav/syfo/dialogmelding/converter/MeldingInfoConverter.kt, src/main/kotlin/no/nav/syfo/dialogmelding/converter/MottakenhetBlokkConverter.kt, src/main/kotlin/no/nav/syfo/dialogmelding/converter/MottakerConverter.kt, src/main/kotlin/no/nav/syfo/dialogmelding/converter/PasientConverter.kt, src/main/kotlin/no/nav/syfo/dialogmelding/converter/SenderConverter.kt, src/test/kotlin/no/nav/syfo/behandler/kafka/KafkaBehandlerDialogmeldingBestillingSpek.kt, src/test/kotlin/no/nav/syfo/dialogmelding/DialogmeldingServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/BehandlerGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FellesformatDialogmeldingXml.kt
Mye skal være på plass her, men gjør det med å hente navn etterpå. 
Må i alle fall hente navn for arbeidstaker, og kanskje også for behandler og organisasjon. Det blir en egen PR.
=> Sende dialogmelding til MQ

src/main/kotlin/no/nav/syfo/dialogmelding/converter/MottakenhetBlokkConverter.kt, src/test/kotlin/no/nav/syfo/dialogmelding/DialogmeldingServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/BehandlerDialogmeldingBestillingGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FellesformatDialogmeldingAvlysningXml.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FellesformatDialogmeldingEndreTidStedXml.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FellesformatDialogmeldingReferatXml.kt
Ref side 36 i løsningsbeskrivelse-dokumentet
=> Set correct ebxml-params

src/main/kotlin/no/nav/syfo/behandler/api/BehandlerDialogmeldingDTO.kt, src/main/kotlin/no/nav/syfo/behandler/domain/Behandler.kt, src/test/kotlin/no/nav/syfo/behandler/api/BehandlerApiSpek.kt
Trenger fnr i BehandlerDialogmeldingDTO slik at Modia kan sende med dette i innkalling til behandler til isdialogmote, og vi der kan validere at svar fra behandler på innkalling har riktig behandler-fnr.
=> Lagt behandler fnr til DTO

src/main/kotlin/no/nav/syfo/application/api/authentication/ApiFeature.kt, src/main/kotlin/no/nav/syfo/behandler/api/BehandlerApi.kt, src/main/kotlin/no/nav/syfo/behandler/api/access/VeilederAPIAccessPipeline.kt
Add common exception handling for API in StatusPages feature and add reusable check of Veileder-access.
=> Add common API exception handling

src/main/kotlin/no/nav/syfo/behandler/partnerinfo/PartnerinfoClient.kt
Add support to request Partnerinfo as system to enable a Person to request a list of Behandler for self in upcoming BehandlerPersonAPI.
=> Add support to request Partnerinfo with system token

src/main/kotlin/no/nav/syfo/behandler/fastlege/FastlegeClient.kt, src/test/kotlin/no/nav/syfo/testhelper/mocks/FastlegeRestMock.kt
Add support to request FastlegeRespons from Fastlegerest as system to enable a Person to request its Fastlege in the upcoming BehandlerPersonAPI
=> Add support to request FastlegeResponse as system

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/behandler/BehandlerDialogmeldingService.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/JacksonKafkaDeserializer.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/KafkaConfig.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/KafkaModule.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/behandlerdialogmelding/BehandlerDialogmeldingBestillingDTO.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/behandlerdialogmelding/KafkaBehandlerDialogmeldingBestilling.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaBehandlerSykmelding.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/sykmelding/ReceivedSykmeldingDTO.kt, src/test/kotlin/no/nav/syfo/behandler/kafka/behandlerdialogmelding/KafkaBehandlerDialogmeldingBestillingSpek.kt, src/test/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaSykmeldingSpek.kt, src/test/kotlin/no/nav/syfo/dialogmelding/DialogmeldingServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/TestKafka.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/BehandlerDialogmeldingBestillingGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/SykmeldingGenerator.kt
Nå klar for review 😊
Bare et "skall" gjør ingenting med sykmeldingene i første omgang. Og konsumering togglet av i både preprod og prod.
=> Consume sykmeldinger

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/JacksonKafkaDeserializer.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/KafkaConfig.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/KafkaModule.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/dialogmeldingfrombehandler/KafkaDialogmeldingFromBehandler.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/dialogmeldingfrombehandler/KafkaDialogmeldingFromBehandlerDTO.kt, src/test/kotlin/no/nav/syfo/behandler/kafka/dialogmeldingfrombehandler/KafkaDialogmeldingFromBehandlerSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmeldingFromBehandlerGenerator.kt
Co-authored-by: John Martin Lindseth john.martin.lindseth@nav.no
=> Consume dialogmeldinger from Padm2 topic

src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaBehandlerSykmelding.kt, src/test/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaSykmeldingSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/SykmeldingGenerator.kt
Har også lagt til flere tester
=> Update system if changed

src/main/kotlin/no/nav/syfo/dialogmelding/converter/MeldingInfoConverter.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FellesformatDialogmeldingXml.kt
Forhåpentligvis midlertidig inntil alle EPJ-systemer støtter at feltet mangler.
Co-authored-by: June Henriksen june.henriksen2@nav.no
=> Add refToParent for first message in conversation

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/behandler/kafka/KafkaConfig.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaBehandlerSykmelding.kt, src/test/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaSykmeldingSpek.kt
Fikser problemer som ble avdekket i forsøket på å prosessere et begrenset antall sykmeldinger
=> Bugfix processing of sykmeldinger

src/main/kotlin/no/nav/syfo/application/ApplicationUtils.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/KafkaModule.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaBehandlerSykmelding.kt
Ble ferdig med å prosessere backlog'en av sykmeldinger i løpet av helga.
=> Cleanup after consuming sykmelding-backlog

src/main/kotlin/no/nav/syfo/application/ApplicationUtils.kt, src/main/kotlin/no/nav/syfo/util/UnboundedDispatcher.kt
All background tasks should now start
=> Allow unbounded dispatchers

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt, src/main/kotlin/no/nav/syfo/behandler/api/BehandlerApi.kt, src/main/kotlin/no/nav/syfo/behandler/database/BehandlerExtendedQuery.kt, src/main/kotlin/no/nav/syfo/behandler/database/BehandlerQuery.kt, src/main/kotlin/no/nav/syfo/behandler/database/domain/PBehandler.kt, src/main/kotlin/no/nav/syfo/behandler/domain/Behandler.kt, src/test/kotlin/no/nav/syfo/behandler/BehandlerServiceSpek.kt, src/test/kotlin/no/nav/syfo/behandler/GetBehandlereSpek.kt, src/test/kotlin/no/nav/syfo/behandler/kafka/dialogmeldingfrombehandler/KafkaDialogmeldingFromBehandlerSpek.kt, src/test/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaSykmeldingSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt, src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/BehandlerGenerator.kt
Co-authored-by: June Henriksen <june.henriksen2@nav.no>
Use new query for pBehandler and type, remove duplicates before returning
=> Return sykmeldingbehandlere to veileder

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
Co-authored-by: June Henriksen <june.henriksen2@nav.no>
=> Read dialogmeldinger from behandler, get all behandlere in dev

build.gradle.kts, src/main/kotlin/no/nav/syfo/App.kt
Should fix vulnerability in ktor-utils, Snyk score: High
=> Upgrade ktor 2.0.0 --> 2.0.1

src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt, src/main/kotlin/no/nav/syfo/behandler/DialogmeldingToBehandlerService.kt, src/main/kotlin/no/nav/syfo/behandler/api/person/PersonBehandlerApi.kt, src/main/kotlin/no/nav/syfo/behandler/database/BehandlerArbeidstakerQuery.kt, src/main/kotlin/no/nav/syfo/behandler/database/domain/PBehandlerArbeidstaker.kt, src/main/kotlin/no/nav/syfo/behandler/domain/Arbeidstaker.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaBehandlerSykmelding.kt, src/main/kotlin/no/nav/syfo/dialogmelding/DialogmeldingService.kt, src/main/kotlin/no/nav/syfo/dialogmelding/converter/FellesformatConverter.kt, src/main/kotlin/no/nav/syfo/dialogmelding/converter/HodemeldingConverter.kt, src/main/kotlin/no/nav/syfo/dialogmelding/converter/MeldingInfoConverter.kt, src/main/kotlin/no/nav/syfo/dialogmelding/converter/PasientConverter.kt, src/test/kotlin/no/nav/syfo/behandler/BehandlerServiceSpek.kt, src/test/kotlin/no/nav/syfo/behandler/kafka/dialogmeldingfrombehandler/KafkaDialogmeldingFromBehandlerSpek.kt, src/test/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaSykmeldingSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt
Fordi "Relasjon" kun hadde informasjon om arbeidstaker og type, ikke behandler, og da er det egentlig ikke en relasjon.
Alternativt må man lage et ekte relasjonsobjekt som har informasjon om begge parter.
=> Replace relasjon with arbeidstaker plus relasjonstype

build.gradle.kts
Tror Snyk blir fornøyd med dette
=> Bump Kafka-embedded

src/test/kotlin/no/nav/syfo/behandler/GetBehandlereSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/BehandlerGenerator.kt
Bruk servermock for fastlege og partnerinfo.
=> Make GetBehandlereSpek an integration test

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, build.gradle.kts, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/application/mq/MQSender.kt, src/main/kotlin/no/nav/syfo/application/mq/MQUtils.kt, src/main/kotlin/no/nav/syfo/behandler/database/BehandlerDialogmeldingBestillingQuery.kt, src/main/kotlin/no/nav/syfo/dialogmelding/apprec/consumer/ApprecConsumer.kt, src/main/kotlin/no/nav/syfo/dialogmelding/apprec/database/ApprecQuery.kt, src/main/kotlin/no/nav/syfo/dialogmelding/apprec/database/domain/PApprec.kt, src/main/kotlin/no/nav/syfo/dialogmelding/apprec/domain/Apprec.kt, src/main/kotlin/no/nav/syfo/dialogmelding/apprec/domain/ApprecStatus.kt, src/main/kotlin/no/nav/syfo/metric/Metrics.kt, src/main/kotlin/no/nav/syfo/util/JAXB.kt, src/main/kotlin/no/nav/syfo/util/XMLDateTimeAdapter.kt, src/main/resources/db/migration/V2_6__alter_table_apprec.sql, src/test/kotlin/no/nav/syfo/dialogmelding/apprec/ApprecConsumerSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt, src/test/resources/apprecError.xml, src/test/resources/apprecOK.xml
Skrudd av i både preprod og prod i første omgang.
=> Process and store incoming apprecs

build.gradle.kts
Nok et forsøk - tror det begynner å nærme seg nå.
=> Fix snyk errors

src/main/kotlin/no/nav/syfo/behandler/database/BehandlerExtendedQuery.kt, src/test/kotlin/no/nav/syfo/behandler/api/BehandlerApiSpek.kt
Med denne endringen vil man få treff på "Stortorget Legekontor" selv om søkestrengen er "legekontor"
=> Gjøre søk på kontornavn mindre case-sensitivt

src/main/kotlin/no/nav/syfo/dialogmelding/converter/MottakerConverter.kt, src/test/kotlin/no/nav/syfo/dialogmelding/DialogmeldingServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/BehandlerGenerator.kt
Ser at mange dialogmeldinger feiler på dette i preprod - det har ikke forekommet i prod ennå, men det kan det godt gjøre.
=> Dialogmelding to mottaker with no orgnr

src/main/kotlin/no/nav/syfo/oppfolgingsplan/OppfolgingsplanService.kt, src/main/kotlin/no/nav/syfo/oppfolgingsplan/converter/FellesformatConverter.kt, src/main/kotlin/no/nav/syfo/oppfolgingsplan/converter/HodemeldingConverter.kt, src/main/kotlin/no/nav/syfo/oppfolgingsplan/converter/MeldingInfoConverter.kt
Hypotesen er at apprec'ene vi nå har begynt å motta er for oppfølgingsplanene vi sender. For å verifisere dette må vi logge msgId ved utsending.
=> Log msgid when sending oppfolgingsplan

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, build.gradle.kts, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/application/kafka/ApplicationEnvironmentKafka.kt, src/main/kotlin/no/nav/syfo/application/kafka/KafkaConfig.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/KafkaConfig.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/KafkaModule.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/dialogmeldingfrombehandler/KafkaDialogmeldingFromBehandler.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/dialogmeldingtobehandlerbestilling/KafkaDialogmeldingToBehandlerBestilling.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaBehandlerSykmelding.kt, src/main/kotlin/no/nav/syfo/identhendelse/kafka/IdenthendelseConsumerService.kt, src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseConsumerConfig.kt, src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseDTO.kt, src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseMetric.kt, src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseTask.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/TestKafka.kt
Gjør også noen refaktoreringer på generell kafka-config.
=> Add identhendelse-config

build.gradle.kts, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt, src/main/kotlin/no/nav/syfo/client/pdl/PdlMetric.kt, src/main/kotlin/no/nav/syfo/client/pdl/domain/PdlHentIdenterRequest.kt, src/main/kotlin/no/nav/syfo/client/pdl/domain/PdlIdenterResponse.kt, src/main/kotlin/no/nav/syfo/client/pdl/domain/PdlPersonResponse.kt, src/main/kotlin/no/nav/syfo/client/pdl/domain/PdlRequest.kt, src/main/kotlin/no/nav/syfo/identhendelse/IdenthendelseService.kt, src/main/kotlin/no/nav/syfo/identhendelse/database/IdenthendelseQuery.kt, src/main/kotlin/no/nav/syfo/identhendelse/kafka/IdenthendelseConsumerService.kt, src/main/resources/pdl/hentIdenter.graphql, src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/KafkaIdenthendelseDTOGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/PdlResponseGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/mocks/PdlMock.kt
HentIdenter fra PDL er i samme PR, men er splittet opp i egen commit hvis det er lettere å review på den måten 👍🏼
=> Add Identhendelse service

src/main/kotlin/no/nav/syfo/dialogmelding/converter/MottakerConverter.kt, src/main/kotlin/no/nav/syfo/dialogmelding/converter/PasientConverter.kt, src/main/kotlin/no/nav/syfo/domain/Personident.kt, src/main/kotlin/no/nav/syfo/oppfolgingsplan/converter/MottakerConverter.kt, src/main/kotlin/no/nav/syfo/oppfolgingsplan/converter/PasientConverter.kt, src/main/kotlin/no/nav/syfo/util/ObjectFactoryMsgHeadUtils.kt, src/test/kotlin/no/nav/syfo/dialogmelding/DialogmeldingServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FellesformatDialogmeldingEndreTidStedXml.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FellesformatDialogmeldingNoHerIdXml.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FellesformatDialogmeldingReferatXml.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FellesformatDialogmeldingXml.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FellesformatDialogmeldingXmlDNR.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/FellesformatMessageXml.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/RSHodemeldingGenerator.kt
Korrigerer dette for både dialogmeldinger og oppfølgingsplaner
=> DNR encoding

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Venter på https://github.com/navikt/isdialogmelding/pull/189
=> Enable identhendelse consumption in prod

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/dialogmelding/apprec/consumer/ApprecConsumer.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Fant tilfeldigvis en uteglemmelse som har ført til at isdialogmelding har restartet en gang i blant helt unødvendig.
=> Remove toggle and apprec read-limit

src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt, src/main/kotlin/no/nav/syfo/behandler/api/BehandlerApi.kt, src/main/kotlin/no/nav/syfo/util/RequestUtil.kt, src/test/kotlin/no/nav/syfo/behandler/api/BehandlerApiSpek.kt
For å kunne hente navn på behandlere og vise frem hvem som har sendt dialogmeldingene, trenger vi å hente dette i noen tilfeller fra dette APIet. 
Se tråd https://nav-it.slack.com/archives/G01ABN2E885/p1680248125499369
=> Add endpoint for getting behandler by behandlerRef

src/main/kotlin/no/nav/syfo/App.kt
isdialogmelding ble ustabil tidligere i dag pga for få tråder.
=> Increase thread pool

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/behandler/DialogmeldingToBehandlerService.kt, src/main/kotlin/no/nav/syfo/behandler/database/BehandlerDialogmeldingBestillingQuery.kt, src/main/kotlin/no/nav/syfo/dialogmelding/apprec/ApprecService.kt, src/main/kotlin/no/nav/syfo/dialogmelding/apprec/consumer/ApprecConsumer.kt, src/main/kotlin/no/nav/syfo/dialogmelding/apprec/domain/Apprec.kt, src/test/kotlin/no/nav/syfo/behandler/kafka/dialogmeldingtobehandlerbestilling/KafkaDialogmeldingToBehandlerBestillingSpek.kt, src/test/kotlin/no/nav/syfo/cronjob/DialogmeldingCronjobSpek.kt, src/test/kotlin/no/nav/syfo/dialogmelding/apprec/ApprecConsumerSpek.kt
Flyttet noe kode ut av consumer og inn i `ApprecService` / `DialogmeldingToBehandlerService` før vi begynner med ny topic for apprec-status på dialogmeldingbestillinger.
=> Refactor ApprecConsumer 🎨 

src/main/kotlin/no/nav/syfo/dialogmelding/status/database/DialogmeldingStatusQuery.kt
Øker limit her så vi får publisert statuser som har hopet seg opp fra vi begynte å lagre til publisering ble skrudd på. Vil tro den rekker å gjøre seg ferdig med å produsere 1000 til topic og oppdatere database på 10 minutter?
=> Increase select limit

src/main/resources/db/migration/V3_5__disable_legevakt_kontor.sql
Unngå at vi sender flere dialogmeldinger til behandlere ved dette kontoret (de stopper opp hos e-mottak).
=> Disable behandlerkontor for legevakt

.github/workflows/codeql.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt, src/main/kotlin/no/nav/syfo/behandler/database/BehandlerKontorQuery.kt, src/main/kotlin/no/nav/syfo/behandler/partnerinfo/PartnerinfoClient.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/VerifyPartnerIdCronjob.kt
Cronjob som logger kontor vi bør undersøke nærmere (fordi dialogmeldinger sendt til behandlere knyttet til kontoret antakelig vil feile).
=> Cronjob verify partnerid

src/main/resources/db/migration/V3_8__disable_behandler_kontor.sql
Meldingene som sendes til kontoret med herId 2170 kommer ikke fram, så disabler kontoret. De vil antakelig "gjenoppstå" med riktig herId etter hvert.
=> Disable kontor med utdatert herId

src/main/kotlin/no/nav/syfo/dialogmelding/apprec/consumer/ApprecConsumer.kt
Fikser kritisk sårbarhet fra code scanning: java/xxe
Se feks https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html
=> Safe unmarshal

src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt
Logger feil når behandlerkontorets herId fra adresseregisteret ikke matcher det vi har persistert for aktuell partnerId i vår database
=> IS-1837: Log kontor feil herid

src/main/resources/db/migration/V4_0__lock_legevakt_kontor.sql
Setter flagg på disse slik at de ikke blir enabled selv om det skulle dukke opp en dialogmelding
=> IS-1837: Lock legevakt-kontor (skal ikke sende dialogmeldinger til disse)

src/main/kotlin/no/nav/syfo/behandler/BehandlerMetric.kt, src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt, src/main/kotlin/no/nav/syfo/behandler/database/BehandlerQuery.kt, src/test/kotlin/no/nav/syfo/behandler/BehandlerServiceSpek.kt
Oppdaterer telefonnr for behandler med det vi får fra adresseregisteret eller via en sykmelding
=> IS-1787: Update behandler telefon

src/main/resources/db/migration/V4_2__update_behandler_herid.sql
Behandler hadde feil herId så meldinger endte opp hos kollega som hadde vært vikar.
=> IS-1857: Oppdaterer herId for behandler

src/main/resources/db/migration/V4_3__update_behandler_kontor_herid.sql, src/main/resources/db/migration/V4_4__update_behandler_herid.sql
Et av kontorene som loggingen har avdekket har utdatert her_id
=> Fix behandler kontor

src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt
Tror vi har fått ryddet unna det viktigste nå i denne omgang, og dessuten logges det en del som vi ikke trenger å gjøre noe med. Så endrer til warn.
=> Log warn instead of error

src/main/resources/db/migration/V4_7__update_behandler_herid.sql
Alle dialogmeldinger sendt til aktuell behandler har fått negativ apprec. Forsøker å legge inn herid for behandleren for å se om det hjelper.
=> IS-1837: Legg inn manglende herId for behandler

src/main/resources/db/migration/V4_8__update_behandler_herid.sql
Retter opp herId for to behandlere
=> IS-1905: Oppdaterer herId for behandler

build.gradle.kts
=> Upgrade deps dec23 again

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
Hva har blitt lagt til✨🌈
Tilgang til ingress fra applikasjonen `lps-oppfolgingsplan-mottak`
i namespace `team-esyfo`.
Mulighet til å sende LPS til fastlege fra applikasjonen
`lps-oppfolgingsplan-mottak`.
=> Add 'lps-oppfolgingsplan-mottak' to accessPolicy to allow relaying of LPS to fastlege/GP

src/main/resources/db/migration/V5_6__disable_behandler_kontor.sql
Fant et kontor til som er duplikat
=> IS-1906: Disabler duplikate behandlerkontor

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
Lagt til aap-oppslag i innbound rules i naiserator.
aap oppslag skal bytte ut aap-søknad-api, og trenger da samme tilgangene.
=> Lagt til aap-oppslag i innbound access policy rules

src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Måtte legge til test-env også, hvis ikke kjører ikke testene.
=> Add testenv for aap-oppslag

.nais/naiserator-prod.yaml, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
=> aap oppslag client id for prod

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt, src/main/kotlin/no/nav/syfo/behandler/database/BehandlerQuery.kt, src/main/kotlin/no/nav/syfo/behandler/fastlege/BehandlerKontorFraAdresseregisteretDTO.kt, src/main/kotlin/no/nav/syfo/behandler/fastlege/FastlegeClient.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt, src/test/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/BehandlerKontorResponseGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/mocks/FastlegeRestMock.kt
Tenkte vi kunne begynne med å deaktivere kontor i vårt register som er deaktivert i Adresseregisteret.
Mange TODOs på oppdatering av behandlere for hvert kontor
=> IS-1821: Cronjob behandlere for kontor

src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt
Ser ut som NHN kneler når cronjob'en kjører, så disable foreløpig.
=> Disable cronjob for now

src/main/resources/db/migration/V5_8__update_behandler_kontor_herid.sql
Oppdaget et kontor som har fått ny herId (og det samme med behandlerene på kontoret)
=> IS-1821: Kontor og behandlere har fått nye herid

src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobUtils.kt, src/main/kotlin/no/nav/syfo/cronjob/SuspensjonCronjob.kt, src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt
Enable cronjob igjen, men nå vil den kjøre hver natt kl 3
=> IS-1821: Kjøre cronJob om natta

src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt, src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt, src/test/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/BehandlerKontorResponseGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/mocks/FastlegeRestMock.kt
Invaliderer behandlere som er inaktive i Adresseregisteret
=> IS-1821: Invalidere inaktive behandlere

src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt
Feilsøker hvilke kontor som går treigt i Adresseregisteret
=> IS-1821: Log response time Adresseregisteret

src/main/resources/db/migration/V5_9__lock_legevakt_kontor.sql
Dette er "kontor" der oppslaget i Adresseregisteret feiler fordi det er kommunale legevakter. Skal ikke sende dialogmeldinger til disse.
=> IS-1821: Disable legevakt-kontor

.nais/kafka/behandler-dialogmelding-bestilling.yaml
Gi datavarehus tilgang til å lese dialogmelding-bestilling topic
=> IS-2081: Give dvh read access to topic

src/main/resources/db/migration/V6_0__update_behandler_herid.sql
Se https://jira.adeo.no/browse/FAGSYSTEM-317415.
Én lege som meldte feil, og hun hadde feil HER-ID (den hun hadde tilhørte en person som var invalidert).
Da jeg slo opp kontoret fant jeg at flere av de aktive legene manglet HER-ID, så oppdaterte de også 👍🏼
=> IS-2067: Update her-id for behandlere at kontor

src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt
- Legger til behandlingsnummer header
=> IS-1477: Add behandlingsnummer header to pdl requests

src/main/resources/db/migration/V6_1__update_behandler_herid.sql
Vi vet ikke akkurat hvorfor det har blitt feil, men vi fant riktig id i Adresseregisteret.
https://jira.adeo.no/browse/FAGSYSTEM-316113
=> IS-2040: Update herID of behandler

build.gradle.kts
=> Bump postgres

build.gradle.kts, src/main/resources/db/migration/V6_3__disable_behandler_kontor.sql
Fikk beskjed fra Parviz om at dette kontoret må deaktiveres
=> Disable inactive kontor

src/main/resources/db/migration/V6_4__update_behandler_herid.sql
Se Jira-sak: https://jira.adeo.no/browse/FAGSYSTEM-321871
=> IS-2190: Update HER-ID for behandler

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/behandler/api/BehandlerSystemApi.kt, src/test/kotlin/no/nav/syfo/behandler/api/BehandlerSystemApiSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Lagt til system api for å hente behandler fra behandlerRef til bruk fra journalføringscronjob i isfrisktilarbeid
=> IS-2258: Add behandler system api for isfrisktilarbeid

src/main/resources/db/migration/V6_5__disable_behandler_kontor.sql
Fikk beskjed fra e-mottak om at dette kontoret ikke skal brukes lengre.
=> IS-2321: Invalider kontor og tilhørende behandlere

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt, src/main/kotlin/no/nav/syfo/behandler/database/BehandlerQuery.kt, src/main/kotlin/no/nav/syfo/client/syfohelsenettproxy/SyfohelsenettproxyClient.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt, src/test/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/BehandlerKontorResponseGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/mocks/FastlegeRestMock.kt, src/test/kotlin/no/nav/syfo/testhelper/mocks/MockHttpClient.kt, src/test/kotlin/no/nav/syfo/testhelper/mocks/SyfohelsenettproxyMock.kt
Revaliderer behandlere vi allerede har hvis de er aktive i AR og er invaliderte hos oss, og legger til nye hvis vi de ikke finnes hos oss fra før. Henter noe informasjon fra HPR (via syfohelsenettproxy).
=> IS-1946: Nye behandlere fra Adresseregisteret (AR)

src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt
Funka fint for det ene kontoret i natt, så forsøker for alle (kjører kl 0300 natt til i morgen)
=> IS-1946: Nye behandler fra AR (for alle aktive kontor)

src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt
Siden den skaper litt ustabilitet i trafikken mot NHN disabler vi batch-job'en igjen.
=> IS-1946: Disable batch-job

src/main/resources/db/migration/V6_6__update_behandler_herid.sql
Noen behandlere hadde feil herId noe som fører til at dialogmeldinger ikke kommer fram (med Pridok EPJ)
=> IS-2416: Korrigere behandlerinformasjon

src/main/resources/db/migration/V6_7__update_behandler_herid.sql
Dialogmøteinnkalling feilet antakelig pga feil herId.
Fant en annen behandler ved samme kontor der det hadde blitt opprettet en duplikat pga feil hprId - rydder opp i det samtidig.
=> IS-2423: Korrigere behandlerinformasjon

documentation/kafka/isdialogmelding-behandler-dialogmelding-bestilling.md
Vi sender ikke kodene, men enum-verdier som mappes om til koder i kodebasen.
=> Add documentation for DialogmeldingKodeverk

src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt, src/test/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
Invaliderer duplikate forekomster av behandlere.
=> IS-2402: Invalidate duplicates

src/main/resources/db/migration/V7_00__fix_wrong_hprid.sql
Fant to behandlere til med feil hprId: setter riktig hprId på disse med en gang,
=> IS-2404: rette opp flere hpr_id

src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt, src/test/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
Invalidere behandlere som ikke finnes for aktuelt kontor i Adresseregisteret.
=> IS-2403: Invalidere behandlere som er ukjent i AR

src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt, src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt, src/test/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/BehandlerKontorResponseGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/mocks/SyfohelsenettproxyMock.kt
Fikser manglende hprId der det er mulig.
=> IS-2405: Repair hprId

src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt, src/main/kotlin/no/nav/syfo/behandler/database/BehandlerQuery.kt, src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt, src/test/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjobSpek.kt
Oppdaterer eksisterende behandler med info fra Adresseregisteret
=> IS-2403: Oppdatere behandlere fra AR

src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
Et av kontorene er det som det ble rapportert om problemer med i https://jira.adeo.no/browse/FAGSYSTEM-339018
=> IS-2581: Tester ut cronjob på fire kontor

src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt
Disabler cronjob igjen i første omgang
=> IS-2581: Disable cronjob etter test

src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt
Noen justeringer etter test-kjøring av cronjob'en
=> IS-2581: Filtrere bort admin-ansatte

src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobUtils.kt, src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt
Justerer slik at cronjob'en mot Adresseregisteret kjører for alle aktive behandlerkontor hver søndag kl 6.
=> IS-2581: Cronjob ukentlig

src/main/resources/db/migration/V7_02__disable_duplicate_kontor.sql
Fant en duplikat forekomst av et behandler_kontor i databasen. Disabler det ene slik at ikke begge blir oppdatert med behandlere fra Adresseregisteret (via cronjob'en).
=> IS-2581: Disable duplikat behandlerkontor

src/main/resources/db/migration/V7_03__lock_legevakt_kontor.sql
Dette er legevakt-kontor som ikke skal benyttes for dialogmeldinger
=> IS-2581: Disable legevakt-behandlerkontor

src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt, src/test/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjobSpek.kt
Aleris er et privat sykehus og har ingen behandlere i Adresseregisteret. Men det sendes og mottas dialogmeldinger, så for å ikke forkludre det så unntar vi Aleris fra de kontorene cronjob'en oppdaterer.
=> IS-2406: cronjob skal ikke oppdatere Aleris

src/main/kotlin/no/nav/syfo/behandler/BehandlerService.kt, src/main/kotlin/no/nav/syfo/behandler/database/BehandlerQuery.kt, src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt, src/main/resources/db/migration/V7_04__cleanup_after_cronjob.sql, src/test/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/BehandlerKontorResponseGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/mocks/SyfohelsenettproxyMock.kt
Fikser en bug og gjør noen justeringer etter full kjøring av cronjob mot Adresseregisteret.
=> IS-2611: Cronjob bugfix og opprydning

.nais/naiserator-dev.yaml
=> Fix db-tier dev

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
Kommer opp som en warning i nais-konsollet, ser ut som aap bruker isdialogmelding fra en annen app (som også ligger i lista)
=> Remove unused access policy

src/main/resources/db/migration/V7_05__activate_kontor.sql
Aktivere dialogmelding for kontor
=> IS-2657: Active behandldlerkontor

src/main/resources/db/migration/V7_07__lock_legevakt_and_kiropraktor_kontor.sql
Noen kontorer til som det ikke er mulig å sende dialogmeldinger til (og som lager krøll i oppdatering fra Adresseregisteret).
=> Disable legevakt- og kiropraktorkontor

src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt
Den aktuelle behandleren er ferdig oppdatert etter søndagens kjøring av cronjob'en.
=> IS-2732: Oppdatere spesifikk behandler fra Adresseregisteret (done)

src/main/resources/db/migration/V7_08__lock_legevakt_and_disable_behandler.sql
Siste rest av advarsler fra cronjob'en som sync'er mot Adresseregisteret. Håper neste søndags kjøring blir helt uten errors/warnings 🤞
=> Disable legevakt-kontor and behandler

src/main/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaBehandlerSykmelding.kt, src/main/kotlin/no/nav/syfo/behandler/kafka/sykmelding/SykmeldingMetrics.kt, src/test/kotlin/no/nav/syfo/behandler/kafka/sykmelding/KafkaSykmeldingSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/SykmeldingGenerator.kt
Kontor uten herId kan ikke brukes til noe i isdialogmelding.
=> IS-2768: Ikke opprette kontor fra sykmelding når kontorets herId mangler

src/main/kotlin/no/nav/syfo/behandler/api/BehandlerDTO.kt, src/main/kotlin/no/nav/syfo/behandler/domain/Behandler.kt, src/test/kotlin/no/nav/syfo/behandler/api/BehandlerApiSpek.kt
AAP trenger å få med hprId når de henter ut behandlere
=> IS-2864: Inkludere hprId i behandler-api

src/main/kotlin/no/nav/syfo/cronjob/CronjobUtils.kt, src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt, src/main/resources/db/migration/V7_12__activate_kontor.sql
Aktiverer behandlerkontor og endrer slik at sync'en mot Adresseregisteret går annenhver dag.
https://jira.adeo.no/browse/FAGSYSTEM-363572
=> IS-3002: Aktiver behandlerkontor

src/main/resources/db/migration/V7_13__lock_legevakt_kontor.sql
Skal ikke sende dialogmeldinger til dette legevakt-kontoret
=> Disable legevakt-kontor

src/main/resources/db/migration/V7_14__lock_legevakt_kontor.sql
Fant noen flere legevakt-kontor som vi må sperre for dialogmeldinger
=> Disable flere legevakt-kontor

src/main/resources/db/migration/V7_15__activate_kontor.sql
https://jira.adeo.no/browse/FAGSYSTEM-371167
=> IS-3133: Aktiver behandlerkontor

src/main/resources/db/migration/V7_16__activate_kontor.sql
Enable dialogmeldinger for kontor
=> IS-3193: Aktiver behandlerkontor

src/main/kotlin/no/nav/syfo/behandler/domain/BehandlerKategori.kt, src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt, src/test/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/BehandlerKontorResponseGenerator.kt
Vi har manglet behandlerkategori for psykolog, så de har ikke blitt opprettet av cronjob'en som henter behandlere fra Adresseregisteret.
=> IS-3207: Opprette psykolog-behandlere fra Adresseregisteret

src/main/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjob.kt, src/test/kotlin/no/nav/syfo/cronjob/VerifyBehandlereForKontorCronjobSpek.kt
This reverts commit 6823f5bea16fd351a61648d948336a2de659aae0.
Reverterer tilbake til vanlig syklus for oppdatering fra Adresseregisteret
=> Revert "IS-3207: Rekjøre oppdatering av kontor (#408)"

src/main/resources/db/migration/V7_18__activate_kontor.sql
Enable dialogmeldinger for kontor
=> IS-3244: Enable behandlerkontor

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
=> IS-3251: Oppgraderer til Postgres 17

src/main/resources/db/migration/V7_19__update_statistics.sql
Oppdaterer db-statistikk (skal merges etter migrering til Postgres 17)
=> IS-3251: Oppdaterer db-statistikk

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
Trenger tilgang for å hente hprId for behandler for journalføring
=> IS-3357: Gi tilgang til isdialogmote og isbehandlerdialog

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Reverts navikt/isdialogmelding#427
=> Revert "give followupplan-backend inbound access"

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
- Gjenoppretter branch som ble revertet
=> give followupplan-backend inbound access

src/main/resources/db/migration/V7_23__activate_kontor.sql
Aktivere behandlerkontor:
https://jira.adeo.no/browse/FAGSYSTEM-397153
=> IS-3428: Aktiver behandlerkontor
